### ISSUE TITLE
中文文件名出问题，提示错误

### ISSUE THREAD

**Issue by sixgodf** [mjau-mjau/files.photo.gallery#16]
中文文件名出问题，提示错误

**Comment by mjau-mjau** [comment]
谷歌翻译：请提供更好的解释，并请发送链接。 我在demo中有几个地方有中文名字：
https://demo.files.gallery/?tests/sorting/%E4%B8%AD%E5%9B%BD

请使用论坛获得支持：
https://forum.files.gallery/
