### ISSUE TITLE
ffmpeg

### ISSUE THREAD

**Issue by dotcomUNDERGROUND** [mjau-mjau/files.photo.gallery#19]
I can access ffmpeg with "ffmpeg" or "/usr/bin/ffmpeg" on my server.

I have tried adding both paths to config. But its not generating thumbs for the videos. 

Do I need anything else? How do I debug why it's not working?

**Comment by mjau-mjau** [comment]
I'm guessing it could be the same issue as here:
https://forum.files.gallery/d/20-ffmpeg-doesnt-work

Please use the [forums](https://forum.files.gallery/) for support.
