### ISSUE TITLE
Icon for iPhone

### ISSUE THREAD

**Issue by 1letzgo** [mjau-mjau/files.photo.gallery#21]
Can you add an iphone homescreen Icon

**Comment by mjau-mjau** [comment]
> Can you add an iphone homescreen Icon

Seems like a good idea. The only challenge, is that Files Gallery is a single file, and I don't want to include additional images just for an apple-touch-icon. I could add the image on CDN (like other Javascript and CSS resources), but this might be a bit invasive for a homescreen icon. Or maybe not.

Anyway, the short term solution is to add a very basic PNG icon as base64. You can add the below to the `<head>` in `index.php` around line `1892` if you like. I will consider what to do for next release.

```html
<link rel="apple-touch-icon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMAAAADABAMAAACg8nE0AAAAD1BMVEUui1f///9jqYHr9O+fyrIM/O8AAAABIklEQVR42u3awRGCQBBE0ZY1ABUCADQAoEwAzT8nz1CyLLszB6p+B8CrZuDWujtHAAAAAAAAAAAAAAAAAACOQPPp/2Y0AiZtJNgAjTYzmgDtNhAsgEkyrqDkApkVlsBDsq6wBIY4EIqBVuYVFkC98/ycCkr8CbIr6MCNsyosgJvsKxwFQhEw7APqY3mN5cBOnt6AZm/g6g2o8wYqb2B1BQcgeANXb0DuwOwNdKcHLgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeA20mArmB6Ugg0NsCcP/9JS8GAKSlVZMBk8p1GRgM2R4jMHu51a/2G1ju7wfoNrYHyCtUY3zpOthc4MgdNy3N/0PruC/JlVAwAAAAAAAAAAAAAAABwZuAHuVX4tWbMpKYAAAAASUVORK5CYII=">
```

Please post future requests in the Files Gallery forums. Github is only as a repository.
https://forum.files.gallery/
