### ISSUE TITLE
is ffmpeg required to be able to run at all?

### ISSUE THREAD

**Issue by martisj** [mjau-mjau/files.photo.gallery#25]
I am just seeing a loading spinner when i try to access the page.

**Comment by martisj** [comment]
and it says in the console output: `sh: 1: ffmpeg: not found`

**Comment by mjau-mjau** [comment]
No FFmpeg is not required. It's only required for optional video preview images.

> I am just seeing a loading spinner when i try to access the page.

This is something else. Check your browser dev tools > network inspector, check the error. Also see this:
https://www.files.gallery/docs/troubleshooting/

> and it says in the console output: sh: 1: ffmpeg: not found

It just means you don't have FFmpeg, but this won't prevent it from working.

Please post support requests in the support forums. Github is only used as a repository.
https://forum.files.gallery/

**Comment by martisj** [comment]
Alright! Thanks I will use the support forums then :pray:
