### ISSUE TITLE
about search

### ISSUE THREAD

**Issue by ufukayyildiz** [mjau-mjau/files.photo.gallery#5]
hi,

great app, congrats.

can we add pdf search ( document search ) feature to this app? Is this possible?

**Comment by mjau-mjau** [comment]
Hi!

Do you mean searching actual text content inside all PDF files? Or do you
mean searching for PDF files by name in all folders?



regards,

Karl

*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent+with+Shift+Signature&utm_medium=Email+Signature&utm_content=General+Email+Group>*

**Comment by mjau-mjau** [comment]
hi! Do you mean searching actual text content inside all PDF files? Or do you mean searching for PDF files by name in all folders?

There is currently just a "filter", which allows searching/filtering files in the current folder. In the future, we plan to add global search, which allows searching for files/folders in all directories.

As for searching text within PDF documents, this is not currently on the agenda.

**Comment by ufukayyildiz** [comment]
hi,

i mean searching text within PDF documents.

thanks.

**Comment by mjau-mjau** [comment]
So if you have 20x PDF documents in one folder, you want to search for the text inside all the PDF files, and then display the PDF files that contain the search? It might be possible to extract text from a PDF with PHP and search, and it might be ok for single files, but searching though multiple PDF files in real-time would be very slow. Also, it would require a specific external PHP plugin like https://www.pdfparser.org/. Sorry, but it doesn't look reasonable.
