### ISSUE TITLE
License

### ISSUE THREAD

**Issue by AmazinAxel** [mjau-mjau/files.photo.gallery#6]
I was wondering about the license of this project, as the source code is available here on Github but there is no license that states what we can do with it. Are we allowed to edit the source code of this project and redistribute it freely, or is a copyright notice required? You can also add a license file with some text that states what a user can do with the software, as seen in most open source projects on Github.

**Comment by mjau-mjau** [comment]
Hi, thanks for asking. Yes the PHP source code is available, but the Javascript code (which is probably 80% of the application) is only provided in minified format, and would therefore not be easy to edit. You are allowed to edit the code and use as you like, but if you want to distribute, I need to look into a license for that. Also, as you probably understand, if you are editing the files, it will be difficult to upgrade to new versions of Files app as they are released. Let me know if you require more info ...

**Comment by AmazinAxel** [comment]
Thanks for your fast response and it sounds all good to me. I recommend that in the future you should add a license file with some text that says what a user can do so that it makes it legally binding or choose a license from [https://choosealicense.com/](https://choosealicense.com/) Thanks, AmazinAxel

**Comment by mjau-mjau** [comment]
Thanks!

**Comment by dorianim** [comment]
Why are you uploading non-free software on Github? There is litterally no point in doin so, as your license disallows what GitHubs primary purpose is - forking and modifying a project

**Comment by mjau-mjau** [comment]
@dorianim You are probably right, but we upload here for maintenance reasons and to match the package at npmjs.com, necessary for fast access, download and CDN distribution. Besides, we have had a few commits to the core index.php. If it offends some users, I will perhaps take it down.
