### ISSUE TITLE
[Enhancement] Option to ignore or hide files and file types

### ISSUE THREAD

**Issue by yduke** [mjau-mjau/files.photo.gallery#7]
Have tried files.photo.gallery locally, some of the default files or system-generated files like:

- .htaccess
- Thumbs.db
- ...
They can not be hidden by modifying the configuration or any other way.
Is there any possibility to add an option to ignore or hide file types like "*.db", ".*" and custom file names "file-to.hide".
That would be great.

**Comment by yduke** [comment]
Sorry I've found `files_exclude` part in config.php, good work, cheers!

**Comment by mjau-mjau** [comment]
Yep, was just about to answer ... Hope you figure it out! New documentation coming shortly ...
