### ISSUE TITLE
escapeshellarg() blocked the Chinese character

### ISSUE THREAD

**Issue by AAlexDing** [mjau-mjau/files.photo.gallery#8]
In line 609 , the function escapeshellarg() may cause the fail of thumbnail generation, if there are Chinese characters in the path.

Maybe add `setlocale(LC_CTYPE, "UTF8", "en_US.UTF-8");` is useful?

**Comment by mjau-mjau** [comment]
Thanks for the tip, it might be useful. Have you tried already with the `setlocale()` fix? We need to use `escapeshellarg()` to escape characters in filenames for the FFmpeg command.

Thanks again.

**Comment by AAlexDing** [comment]
Yes,it works.   Another error I found is that if the path contains spaces, the thumbnail generation will also report an error. So I just  added a `"` symbol before and after  `escapeshellarg($path)`.  I don't know if it may cause another errors,but it can work now. Maybe you should reconsider about this part.

**Comment by Monter** [comment]
Changing the locale doesn't always help. I have just added a pull request to solve the problem of special characters in folder and file names, and by the way I was able to optimize the creation of thumbnails for video files - the fix significantly speeds up this process.
